sudo: required

services: docker

before_install:
    - docker build -t --no-cache tentativafc/bootcamp-pi-test -f ./Dockerfile.dev .

script:
    - docker run tentativafc/bootcamp-pi-test pytest

after_success:
    ### Login into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build --no-cache -t $DOCKER_USERNAME/bootcamp-pi .    
    - docker push $DOCKER_USERNAME/bootcamp-pi

deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: us-east-1
    app: bootcamp-pi
    env: BootcampPi-env
    bucket_name: elasticbeanstalk-us-east-1-779882487479
    edge: true
    on:
        branch: master

after_deploy:
    - echo "done deploying"


